artifacts_root: artifacts

#Data Ingestion config yaml file
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kafu77/DataSets_repo/raw/main/archive%20(2).zip
  local_data_file: artifacts/data_ingestion/archive%20(2).zip
  unzip_dir: artifacts/data_ingestion


#Data validation config yaml file
data_validation:
  enabled: true
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]


#Data Transformation config yaml file
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


#Model trainer config yaml file

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail


#Model evaluation config yaml file

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv

