artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kafu77/DataSets_repo/raw/main/archive%20(2).zip
  local_data_file: artifacts/data_ingestion/archive%20(2).zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  enabled: true
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]


